### ISSUE TITLE
Missing non standard badge on ListGroups macro

### ISSUE THREAD

**Issue by gsouquet** [mdn/kumascript#1020]
Hi,

I was looking at the page https://developer.mozilla.org/en-US/docs/Web/API and could see that some Specifications have a "not standardised" badge adjacent to their name, the `FileSystem API` being a good example.

However I started noticing a weird thing, it looks like `FMRadio API` should also have that badge displayed. However that is not the case.

Looking at the page source it looks like it is using the `ListGroups` macro. Which will load the `NonStandardBadge`, `ObsoleteBadge`, `DeprecatedBadge` or the `ExperimentalBadge` based on the wiki page tags.

```
if (tags) {
      if (containsTag(tags, "Non-standard") || containsTag(tags, "Non standard")) {
        badge = " " + template("NonStandardBadge", ["1"]);
      }
      // ...
}
```

Looking at the [FMRadio API](https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/API/WebFM_API) example again, it looks like it has the right set of tags on the page, it however does not display the badge correctly

There does not seem to be a lot of differences with the [FileSystem API](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API) page. The only noticeable difference is that the `FMRadio API` is archived and the other one isn't.

I'm a bit unsure about the steps that needs to be taken to fix that. I'd be happy to help if someone can explain briefly how I can debug and test that.

Thank you

**Comment by jwhitlock** [comment]
The FMRadio API is archived, but the link on that page is:

https://developer.mozilla.org/en-US/docs/Web/API/WebFM_API

I would expect the FMRadio API to not appear on this page at all. It may be fixed by the changes for https://bugzilla.mozilla.org/show_bug.cgi?id=1404669

**Comment by ExE-Boss** [comment]
The reason why WebFM, along with other non‑standard archived APIs appears on https://developer.mozilla.org/docs/Web/API is because of the fact that [{{ListGroups}}](https://github.com/mdn/kumascript/blob/master/macros/ListGroups.ejs) has no way to determine if the page has been moved and to where it has been moved.

Also, redirects don’t have tags.

---

See also https://github.com/mdn/kumascript/pull/969, which will help with a similar issue, but for sidebars.
