### ISSUE TITLE
Installation Doesn't Work

### ISSUE THREAD

**Issue by jbrandes** [mdn/kumascript#1024]
I am trying to install Kuma to run MDN but I have spent the past three days stuck on:

Download and load the sample database:

wget -N https://mdn-downloads.s3-us-west-2.amazonaws.com/mdn_sample_db.sql.gz
docker exec -i kuma_web_1 bash -c "zcat | ./manage.py dbshell" < mdn_sample_db.sql.gz

Alternatively, you can use curl (installed by default on macOS):

curl -O https://mdn-downloads.s3-us-west-2.amazonaws.com/mdn_sample_db.sql.gz
docker exec -i kuma_web_1 bash -c "zcat | ./manage.py dbshell" < mdn_sample_db.sql.gz

I keep getting the error:  docker exec -i kuma_web_1 bash -c "zcat | ./manage.py dbshell" < mdn_sample_db.sql.gz
Error: No such container: kuma_web_1

Can anyone help?

**Comment by jwhitlock** [comment]
@jbrandes if ``docker ps`` shows something like ``kuma_web_1_3d980e2f0203``, then you'll need to use that name instead. The docs are in the process of being updated for this change in Docker Compose behavior, see https://github.com/mozilla/kuma/pull/5127
