### ISSUE TITLE
{{event}} macro produces links to old URLs in the all loclaes except en-US

### ISSUE THREAD

**Issue by mfuji09** [mdn/kumascript#1029]
The URLs of the documents of events have been moved in the all locales, however {{event}} macro still produces links to old URLs for them, in the all loclaes except en-US.

old: /<locale>/docs/Web/Reference/Events/
new: /<locale>/docs/Web/Events/

**Comment by mfuji09** [comment]
Please review and merge this pull request to fix it:
https://github.com/mdn/kumascript/pull/1004

**Comment by Watilin** [comment]
I support this issue. Here is an example with the `fr` locale: the page

    https://developer.mozilla.org/fr/docs/Performance/Scroll-linked_effects

links to

    https://developer.mozilla.org/fr/docs/Web/Reference/Events/scroll

(the link is displayed red). Target page is then resolved into

    https://developer.mozilla.org/en-US/docs/Web/Events/scroll
