### ISSUE TITLE
Retire this repo and move the KumaScript server and macros into the Kuma repo

### ISSUE THREAD

**Issue by davidflanagan** [mdn/kumascript#1034]
For https://bugzilla.mozilla.org/show_bug.cgi?id=1509430 I've basically rewritten the KumaScript server to simplify and modernize it. The rewritten code is currently in a PR against the Kuma repo. That is: the PR just abandons this repo and puts the KumaScript server directly inside the Kuma repo. (See https://github.com/mozilla/kuma/pull/5174)

I'm likely to actually create a PR against this repo and land it here first, but I also think that we should seriously consider retiring this repo and putting KumaScript and its macros directly inside the Kuma repo, so I'm opening this issue for discussion.

@jwhitlock has a lot of thoughts about this and points out that beyond the technical issues, there are a number of process issues involved. For instance, if we do the move, then KumaScript bugs will have to be filed on Bugzilla instead of on Github.  Here's what John wrote:

> We'll need to adjust the development environment, Jenkins, and TravisCI. I think that's somewhere between 4 to 16 hours of work.

> We'll also need to use the Kuma development process for the KumaScript engine. In the near term, this means archiving the KumaScript repo, moving the documentation into the Kuma docs, and updating them for the new process. It means closing all open issues, and making people re-open them as Bugzilla bugs. Pull requests will be closed, and will need to be reopened against Kuma, with a bug number, branch name, etc. as specified in CONTRIBUTING.md. This is another few days of cleanup..

> In the medium term, we'd need to reject PRs that update translations and specifications. We'd want to move translations to Pontoon, which requires adding a gettext-compatible library and some other changes (see bug 1340342). We'd want to move data to mdn/data, and formalize how that data is included into KumaScript (not via a GET to github...). We'd also need to accelerate the effort to write unit tests for the macros, to help with this process. We're also not giving merge permissions to the same people that have it on mdn/kumascript, so we'd be taking over more of the code review, testing, and merging ourselves. This may take a few sprints to get to normal.

What do you think @escattone @schalkneethling @Elchi3 @wbamberg?

**Comment by ExE-Boss** [comment]
I feel like that this would be more trouble than it’s worth, given what @jwhitlock said.

**Comment by Elchi3** [comment]
First of all, amazing work @davidflanagan :+1: Happy New Year! Really happy to see something like this as one of the first things in the new year \o/

Generally, I'm in favor of simplifying and so if we save a lot of effort and time for MDN development and deployment, then yes, lets get rid of the submodule and merge everything into Kuma.

However, I agree with John that there are probably a few things that complicate this, so I would prefer to do this in phases. 
First, land the refactored KumaScript in the KumaScript repo, then work on retiring and closing out issues and PRs on that repo and finally move everything into Kuma which involves a bit more as we need to see what that means for Kuma and bug backlogs and governance. 
We might want to think about using GitHub issues as well for Kuma and think through who will be able to review and merge what. These non-code discussions and changes take a bit of time and imo shouldn't depend on your massive refactoring work for now :-)

**Comment by escattone** [comment]
After thinking about this more, I'd prefer as well that this be done in two steps: first land it in the kumascript repo, get it working and deployed from there, and then move on to the task of moving the kumascript code into the kuma repo and retiring the kumascript repo.

**Comment by jwhitlock** [comment]
@davidflanagan, thanks for re-opening this work as #1035. It sounds like retiring this repo is still desired, and should be tracked as an epic / user stories in our sprint planning.
