### ISSUE TITLE
Requesting code freeze of GroupData and InterfaceData

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/kumascript#1043]
GroupData and InterfaceData are being migrated to&nbsp;<code>mdn&#x2011;data</code> in&nbsp;https://github.com/mdn/data/pull/342 and&nbsp;https://github.com/mdn/kumascript/pull/1041, and&nbsp;I&nbsp;don’t wish to&nbsp;have to&nbsp;keep updating https://github.com/mdn/data/pull/342 every&nbsp;time a&nbsp;PR&nbsp;like&nbsp;https://github.com/mdn/kumascript/pull/988 gets&nbsp;merged.

**Comment by jwhitlock** [comment]
It is too early for a code freeze. I think we're at least a month away from migrating ``GroupData`` and ``InterfaceData`` to ``mdn-data``, and there are several steps to take first. For example, we need to move to a local data model to load this data, similar to BCD data.

**Comment by ExE-Boss** [comment]
Also there’s https://github.com/mdn/data/issues/240#issuecomment-418479029.
