### ISSUE TITLE
AddonSidebar / WebExtAPISidebar throws an error on non en-US pages

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kumascript#1052]
Steps to reproduce:
1. See a new user was confused for their first edit https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/i18n$revision/1454348
1. Go to https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/i18n
2. Analyze the stack trace
3. Go to https://github.com/mdn/kumascript/blob/master/macros/WebExtAPISidebar.ejs
4. https://github.com/mdn/kumascript/commit/f0c90cd7304a5637d4b9e93467bce4c6cb8c5c4a#diff-5b074230ba5f6a346cf8b6c2f86d46a6R51 uses `text` which is not declared

Actual result:
An error using AddonSidebar or WebExtAPISidebar throws an error.

Expected result:
The sidebar is displayed equally for all locales.

Notes:
This doesn't occur for every locale. I did not have the time to analyze this further but ja/fr seems affected while es/ko are not.
I will open a small PR to propose a fix about this. However:
- I don't have a local environment dev so please discard it if you feel this fix is not secure
- I didn't analyze the rest of the codebase

Stack trace:

 ```
Error rendering macro 'AddonSidebar' at line 1, column 6 of document:
    1 | <div>{{AddonSidebar}}</div>
-------------^
    2 | 
    3 | <p>Fonctions pour internationaliser votre extension. Vous pouvez utiliser ces API pour obtenir des chaînes localisées à partir des fichiers de locale fournis avec votre extension, connaître la langue actuelle du navigateur et connaître la valeur de son <a href="/fr/docs/Web/HTTP/Content_negotiation#The_Accept-Language_header">En-tete Accept-Language</a>.</p>
/app/macros/AddonSidebar.ejs:379
    377|       <details <%=currentPageIsUnder('WebExtensions/API')%>>
    378|         <summary><%=text['WebExtensions/API']%></summary>
 >> 379|         <%-await template("WebExtAPISidebar", [])%>
    380|       </details>
    381|     </li>
    382| 

/app/macros/WebExtAPISidebar.ejs:1
 >> 1| <%
    2| 
    3| var output = "";
    4| var pageModule = page;

text is not defined;
```

**Comment by SphinxKnight** [comment]
@davidflanagan if this is still "fresh" to you and you have minutes to spare, I'll appreciate your feedback and analysis :)

**Comment by jwhitlock** [comment]
Also filed by @wbamberg as https://bugzilla.mozilla.org/show_bug.cgi?id=1522206

**Comment by davidflanagan** [comment]
As part of that big patch, I noticed that SidebarUtilities was only being used by WebExtAPISidebar, so I just copied it directly into that macro and deleted the separate utilities macro. But it does not appear that the text[] array was defined before this either, so I suspect that the regression here is simply that the bug is being reported now and previously it was swallowed silently, maybe?

Other sidebar macros define a text[] array from values read from L10n:Common, and I think we can fix this by just doing the same for WebExtAPISidebar

**Comment by davidflanagan** [comment]
@SphinxKnight I see that you're planning a PR for this, but since we're in such different timezones, I think I'm just going to go ahead and assign the issue to myself...

**Comment by SphinxKnight** [comment]
@davidflanagan you're right that this is not a regression per se (at least I don't have such an indication) . Sorry about this :/
Regarding the PR, I'll be able to offer something over the week-end.

**Comment by davidflanagan** [comment]
@SphinxKnight : No need to apologize! Thank you for bringing this to our attention

**Comment by davidflanagan** [comment]
PR #1053 fixes this
