### ISSUE TITLE
Is there an alternative to replace the macro ArticlesByTag?

### ISSUE THREAD

**Issue by duduindo** [mdn/kumascript#1059]
## Request type
* [x] Correction or update

## Page to change
https://developer.mozilla.org/pt-BR/docs/Aprender/Design_e_acessibilidade

## Details
The ArticlesByTag was removed: https://github.com/mdn/kumascript/pull/387

**Comment by duduindo** [comment]
Sounds good. I've redirected to [/pt-BR/docs/Learn/Common_questions](https://developer.mozilla.org/pt-BR/docs/Learn/Common_questions).

Thanks!

**Comment by jwhitlock** [comment]
Even better. I'm a bit embarrassed that I confused ``pt-BR`` and ``pr-PT`` 😢
