### ISSUE TITLE
We should dependency-check in CI

### ISSUE THREAD

**Issue by peterbe** [mdn/kumascript#1128]
https://github.com/mdn/kumascript/pull/1125 uncovered (through the use of pnpm instead of npm by the way) that we had packages we *depended* on but weren't directly mentioned in `package.json`. 

We should have caught this earlier and the next time it happens. 

https://www.npmjs.com/package/dependency-check looks promising based on skimming its README. 

As far as I can see [we're not running this in TravisCI](https://github.com/mdn/kumascript/blob/e3fce8ec751f8ffedbdd6527bd7a6e3ab14c6c6b/.travis.yml#L27)

**Comment by ExE-Boss** [comment]
The problem with [dependency-check](https://www.npmjs.com/package/dependency-check) is that it depends on a single entry point and will then recursively scan all `require()` calls, so we’d need to run it for each test file separately, which would slow down the already slow build by the number of test files.

**Comment by peterbe** [comment]
Gross! Sounds really slow. Any idea what that means in seconds? 

I tried to run it locally but it didn't even find out that anything was missing check your [recent PR](https://github.com/mdn/kumascript/pull/1125) clearly demonstrated. My `master` is behind on that commit so it should have caught it. In other words, I don't think I know how to use `dependency-check`. 

Either way, we should really have *something* that prevents [that](https://github.com/mdn/kumascript/pull/1125) for having happened in the first place.
