### ISSUE TITLE
Chinese breadcrumb navigation on en-US page

### ISSUE THREAD

**Issue by SebastianZ** [mdn/kumascript#1200]
The [US English SVG `baseProfile` page](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseProfile) has a Chinese breadcrumb navigation.

I see no difference to other en-US pages for SVG, though that's the only one where this issue occurs, as far as I can tell.

Sebastian

**Comment by SphinxKnight** [comment]
Hi @SebastianZ  :)

The parent of the page was zh-CN, I've changed it for the en-US counterpart and it worked like a charm :)

I'm closing the issue but let me know if you need me to reopen it.
Respectfully,
Julien

**Comment by SebastianZ** [comment]
It works fine now. Merci! :-)
Though can you please tell me where you changed that? Either I was away for too long and just forgot about that option or I don't have the right to change it.

Sebastian

**Comment by SphinxKnight** [comment]
@SebastianZ I had to use some of the admin tools to do that and I'd guess you don't have the right to do so.

**Comment by SebastianZ** [comment]
Ah, that explains it. Everything fine then.

Sebastian
