### ISSUE TITLE
Reveal BCD ID in rendered HTML

### ISSUE THREAD

**Issue by peterbe** [mdn/kumascript#1238]
Running `{{Compat('foo.bar')}}` will yield something like 
```html
<div class="bcd-data">
  ...
</div>
```

When reverse-engineering the rendered HTML it's impossible to know what that ID *was*. This output would be better:

```html
<div class="bcd-data" data-bcd-id="foo.bar">
  ...
</div>
```

There are at least to project efforts that would benefit from this:

1. In `stumptown-content` we're trying to *scrape* MDN URLs and try to stitch together the structure from the rendered HTML into blocks of Markdown and other structured bits. 
2. In `stumptown-renderer` we're trying to write a fallback for MDN URLs that haven't been manually (scraped or by hand) so we can display "legacy Kuma" docs somewhat OK until it's been fully migrated.

**Comment by peterbe** [comment]
Another option is to include it in the Document JSON API. To actually do that we'd need to do a regex on the raw content but it wouldn't be that hard.

**Comment by peterbe** [comment]
@wbamberg @Elchi3 This is blocking me from progressing on the stumptown solution that renders legacy (kuma) documents alongside stumptown documents.

**Comment by Elchi3** [comment]
I can add it to the macro output, if you want me to.

**Comment by peterbe** [comment]
@Elchi3 I already have a change but I'm not sure how to test it in Kuma.
