### ISSUE TITLE
Add "DOM" as a synonym for "DOM WHATWG" in SpecName.ejs

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kumascript#1242]
Currently, if you're trying to refer to the DOM specification, you're expected to use "DOM WHATWG" when using macros such as `APIRef`. This is a case where that can be confusing, as it's the main DOM spec we refer to. I propose adding to the `SpecName` macro the ability to translate the name "DOM" to "DOM WHATWG" so we can use it as a synonym.

**Comment by ExE-Boss** [comment]
This&nbsp;will&nbsp;then be&nbsp;inconsistent with&nbsp;**HTML**, which&nbsp;is&nbsp;currently named&nbsp;“**HTML&nbsp;WHATWG**” in&nbsp;**SpecData.json**.
