### ISSUE TITLE
"user-select" is not listed on /docs/Web/CSS/Reference

### ISSUE THREAD

**Issue by Timwi** [mdn/kumascript#1246]
The `user-select` CSS property is not listed on [/docs/Web/CSS/Reference](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference).

I tried to add it, but you guys made this too convoluted and impenetrable. I dug through the scripts and sources and eventually ended up at [what seems to be the original source of the data](https://github.com/mdn/data/blob/master/css/properties.json), but this file _does_ list `user-select`, so I don’t know whether it’s using the wrong source or whether it’s a bug in the script that generates the index.

**Comment by abdnh** [comment]
I guess changing the `status` property from `nonstandard` to `standard` [as it should be](https://github.com/mdn/data/issues/424) will cause it to be listed? Could someone confirm that?
