### ISSUE TITLE
csssyntax returns incorrect result for shape-image-threshold

### ISSUE THREAD

**Issue by jmswisher** [mdn/kumascript#1254]
See https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/shape-image-threshold#Syntax

The description (correctly) says it is an \<alpha-value> . The Formal Syntax, which uses {{csssyntax}}, says it is a \<number> (incorrect, or at least incomplete).

The info in mdn/data appears to be correct: properties.json has:
 ```
"shape-image-threshold": {
    "syntax": "<alpha-value>"'
```
syntaxes.json has:
```
"alpha-value": {
    "syntax": "<number> | <percentage>"
  },
```
So I would expect the Formal Syntax to show ```<number> | <percentage>```. Is the ```| <percentage>``` part getting dropped somewhere?

**Comment by wbamberg** [comment]
@jmswisher , this seems right now? It looks as if the data was updated in https://github.com/mdn/data/pull/390, but the mdn/data hadn't released a new version of the npm package, which would explain why it looks OK in mdn/data but not in Kuma.

Closing, but of course please reopen if you don't agree.
