### ISSUE TITLE
{{InheritanceDiagram}}: Add a header and/or border to help identify them

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kumascript#126]
Currently, our inheritance diagrams don't stand out well. They're not being used in an "Inheritance" section; instead, they're dropped in the intro text and left to do their own thing. There's nothing explaining what you're seeing or why it's there.

We should have the macro output a heading and/or draw a box around the diagram with a caption, to make it look like a figure.

**Comment by SebastianZ** [comment]
It's a good idea to let the template output a heading. I just want to point out that this is different to any other templates we have. Not sure whether we then still need a border. Other items don't have a border either.

Sebastian

**Comment by a2sheppy** [comment]
Here are a couple of very quick mockups of what I imagine for this.

First, we have the diagram as a section: https://www.dropbox.com/s/hts0y5x9ougwlvs/InheritanceAsSection.png <https://www.dropbox.com/s/hts0y5x9ougwlvs/InheritanceAsSection.png>

Then we have the diagram as a figure: https://www.dropbox.com/s/639u9mg1lzyl093/InheritanceAsFigure.png <https://www.dropbox.com/s/639u9mg1lzyl093/InheritanceAsFigure.png>

I think I prefer the latter, which would simply be embedded into the introduction section the way we currently have the diagrams. But I could go either way.

The blurb of text under the heading is unneeded but I think it just flows better with some text there.

> On Feb 25, 2017, at 9:02 AM, Sebastian Zartner <notifications@github.com> wrote:
> 
> It's a good idea to let the template output a heading. I just want to point out that this is different to any other templates we have. Not sure whether we then still need a border. Other items don't have a border either.
> 
> 


Eric Shepherd
Senior Technical Writer
Mozilla Developer Network <https://developer.mozilla.org/>
Blog: https://www.bitstampede.com/
Twitter: https://twitter.com/sheppy
