### ISSUE TITLE
lint error is blocking builds

### ISSUE THREAD

**Issue by escattone** [mdn/kumascript#1269]
The following `eslint` error is breaking builds:

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/3743693/67814499-726c9080-fa61-11e9-9f8c-5bfbcc2ebed1.png">

It's annoying, because in our case, the `First argument must be name  jest/valid-describe` linting error is a total false alarm, and in fact, the check itself is deeply flawed (for example, see discussion at https://github.com/jest-community/eslint-plugin-jest/issues/203).

**Comment by ExE-Boss** [comment]
What environment is that in the screenshot?

**Comment by escattone** [comment]
> What environment is that in the screenshot?

It's Jenkins with its `Blue Ocean` UI.
