### ISSUE TITLE
Dockerfile uses Python 2.7

### ISSUE THREAD

**Issue by callahad** [mdn/kumascript#1274]
The kumascript Dockerfile calls `npm config set python /usr/bin/env/python2.7` to tell `node-gyp` which Python to use when building native extensions for Node.

Python 2.7 goes end-of-life at the end of the year.

We should update that to a compatible Python 3 and make sure everything still builds and runs as expected.

**Comment by callahad** [comment]
See https://github.com/nodejs/node-gyp#configuring-python-dependency for info on how node-gyp finds a Python to use

May be more obvious to just set the `PYTHON` environment variable (and add a comment in the Dockerfile as to why)

**Comment by escattone** [comment]
Thanks for opening this issue @callahad! This has been on my mind for some time, and I started work on a resolution for this a while back, but was pulled into something else before I could submit a PR and then I forgot about it in the midst of everything else going on. My original thought here was that we should remove any explicit configuration of Python altogether, and just use whatever comes bundled within the `node` image, and I think that still applies. See https://github.com/mdn/kumascript/pull/1278
