### ISSUE TITLE
Index macro replaces pointy brackets with &lt; and &gt;, which is not actually desirable for HTML reference pages

### ISSUE THREAD

**Issue by jmswisher** [mdn/kumascript#1277]
# Steps to reproduce
1. Go to the [HTML index page](https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Index). 
2. Scroll down to the elements (around row 43). 
3. Notice that the page titles are listed as things like "&lt;a&gt;: The Anchor element".

Ideally, the pointy brackets would be preserved. I don't know if there are any page titles with pointy brackets that are there for markup purposes; I don't think so.

**Comment by velusgautam** [comment]
<img width="1132" alt="Screenshot 2019-11-10 at 23 33 44" src="https://user-images.githubusercontent.com/8556085/68552013-a9a05180-0412-11ea-8169-c3df348ca4a7.png">
@jmswisher you mean to correct like the <a> in the green box right?
