### ISSUE TITLE
Update semver query for BCD for 1.0.0

### ISSUE THREAD

**Issue by Elchi3** [mdn/kumascript#1279]
Next week, BCD is going to release 1.0.0 (instead of 0.0.100)

It is a soft release not containing any breaking changes, but it marks the start of us using semver correctly. KumaScript needs to be updated for this in the  package.json:

https://github.com/mdn/kumascript/blob/421795d4871a93f2bbd50015745f305c7fde7b0a/package.json#L29

cc @escattone

**Comment by escattone** [comment]
Thanks @Elchi3! https://github.com/mdn/kumascript/pull/1280 is ready for next week!

**Comment by Elchi3** [comment]
Thank you Ryan! Confirming that BCD 1.0.0 is live.
