### ISSUE TITLE
Provide ability to render multiple data points/trees in a single BCD table

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/kumascript#1307]
We sometimes come up against instances where it'd be useful to be able to render multiple multiple data points/trees in a single BCD table. For example, in this page it'd be so much neater to show these trees in one table in some way:

https://developer.mozilla.org/en-US/docs/Web/CSS/gap#Browser_compatibility

**Comment by peterbe** [comment]
`stumptown-renderer` has a great React component for rendering BCD tables. Its "inspired" by the KS one. It's probably more susceptible to deep changes like this. 

What we're doing with Yari is that we're going to use this new React component both for legacy content and for stumptown (aka. structured) content. Meaning, we can benefit from this sooner than the structure content is ready. 

Simply turning it into an array [0] it should be easy to do. What's not obvious is how to visually make the split. Like, on that page there's 1 row, 3 rows, 1 row spread across 3 tables. If we put them all into one table, shall we just have 1+3+1 rows or should there be a bold border or something that separates them visually in lieu of having separate tables?

[0] Or rather, something like:
```diff
+if (!Array.isArray(compat)) {
+  compat = [compat];
+}
-return <RenderCompat compat={compat}/>
+return <RenderCompats compat={compat}/>
```

**Comment by peterbe** [comment]
Note-to-self; 
Most pages have...
```html
<h2>Browser Compatability</h2>
<div class="bc-data">...</div>
```

Some pages, like [/Web/CSS/gap](https://developer.mozilla.org/en-US/docs/Web/CSS/gap#Browser_compatibility) have:
```html
<h2>Browser Compatability</h2>
<h3>Sub heading 1</h3>
<div class="bc-data">...</div>
<h3>Sub heading 2</h3>
<div class="bc-data">...</div>
```
And [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs) has:
```html
<h2>Sub heading 1</h2>
<div class="bc-data">...</div>
<h2>Sub heading 2</h2>
<div class="bc-data">...</div>
<h2>Sub heading 3</h2>
<div class="bc-data">...</div>
```
It's relevant for Yari and it's relevant for the Browser Set stuff.
