### ISSUE TITLE
LearnBox macro is failing on Korean docs

### ISSUE THREAD

**Issue by alattalatta** [mdn/kumascript#1309]
```
Error compiling macro 'LearnBox' at line 37, column 4 of document:
   35 | </div>
   36 | 
   37 | <p>{{LearnBox({"title":"Random glossary entry"})}}</p>
-----------^
   38 | 
   39 | <h2 id="다루는_항목">다루는 항목</h2>
/app/macros/LearnBox.ejs:1
 >> 1| <%
    2| // This template display a box with a random article to learn from
    3| //
    4| // Params

Unexpected token < in JSON at position 3;
```
It seems the macro body is being treated as an JSON?

The error happens on any page, with or without arguments. Even a normal `LearnBox` will break once its page updates. Reverting the change doesn't work.

I couldn't reproduce it with other languages. Tried with en-US, ja, zh-CN, and zh-TW.

Example: https://wiki.developer.mozilla.org/ko/docs/Learn

**Comment by peterbe** [comment]
It's a fundamental flaw in KumaScript. 
The [`fetchHTTPResource`](https://github.com/mdn/kumascript/blob/d60eaf86bb6304b9f166f28b416b2fa7d4ef3ee4/src/api/mdn.js#L180-L205) function always assumes that if there was not an error *talking* to Kuma, that the response is 200 OK and JSON.
```javascript
        function to_cache(next) {
            try {
                request(opts, (error, response, body) => {
                    if (error) {
                        next(null);
                    } else {
                        next(body);
                    }
                });
            } catch (e) {
                next(null);
            }
        }

```
Hence the cryptic error which redirects the blame to the macro. 


However, at the time of writing, I triggered a refresh of https://wiki.developer.mozilla.org/ko/docs/Learn and it seems to have cleared away the problem. It's a shame that it got itself into this trouble and it *will* happen again sooner or later to some other document.

**Comment by alattalatta** [comment]
@peterbe So it was the caching of the 200/error response at server side? Anyway the issue itself is now resolved so I should close this. Thank you.
