### ISSUE TITLE
Javascript Demo editor does not recognize nullish coalescing operator

### ISSUE THREAD

**Issue by valgrimm** [mdn/kumascript#1312]
Referred by Melissa Thermidor.
Source: Tweet https://twitter.com/sliqric/status/1218106831152852992?s=21

Poster says "I think the editor does not currently recognize the nullish coalescing operator (??) "
in regard to 

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/4b88ac95-3eff-4450-b3c4-44e9d1c61b80)

**Comment by valgrimm** [comment]
Please delete this ticket, I posted it in the wrong place. Sorry :P

**Comment by Elchi3** [comment]
See https://github.com/mdn/sprints/issues/2698
