### ISSUE TITLE
Different color for flagged features?

### ISSUE THREAD

**Issue by saschanaz** [mdn/kumascript#1346]
![image](https://user-images.githubusercontent.com/3396686/76710862-29189700-670b-11ea-8b8f-e242221c1cb9.png)

Bit weird to see flagged features are colored as green, as those features are disabled by default. Shouldn't they be something like yellow?

**Comment by Elchi3** [comment]
Yellow or red would make more sense, I agree.

See also https://github.com/mdn/kumascript/pull/701 and https://bugzilla.mozilla.org/show_bug.cgi?id=1449340
