### ISSUE TITLE
use @mdn/browser-compat-data rather than deprecated mdn-browser-compat-data

### ISSUE THREAD

**Issue by escattone** [mdn/kumascript#1425]
See https://github.com/mdn/browser-compat-data/issues/6640

**Comment by escattone** [comment]
cc @ddbeck Just FYI, for the next push we'll be using `@mdn/browser-compat-data` rather than `mdn-browser-compat-data` (see https://github.com/mdn/kumascript/pull/1427). Thanks for all of your help with https://github.com/mdn/browser-compat-data!

**Comment by ddbeck** [comment]
Excellent news. Thank you, @escattone!
