### ISSUE TITLE
browserAction.openPopup not present in AddonSidebar

### ISSUE THREAD

**Issue by ariasuni** [mdn/kumascript#1442]
The WebExtensions [`browserAction.openPopup()`](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup) function exists but is not present in the sidebar, see screenshot.

![image](https://user-images.githubusercontent.com/2446451/99560670-6a61f480-29c6-11eb-80cf-b8d1547b8e25.png)

**Comment by peterbe** [comment]
It's fragile system these sidebars. Great find though!
The explanation is that the openPopup page lacks the `Method` tag. I've tested this locally in Yari. 
[Go ahead and add `Method` to the list of tags](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup$edit) and it'll resolve that it now gets included in the sidebar. 

Will you close this issue when you get it working?

**Comment by ariasuni** [comment]
I just added the tag but it doesn’t seem to change anything yet. Is this supposed to take some time?

**Comment by peterbe** [comment]
> I just added the tag but it doesn’t seem to change anything yet. Is this supposed to take some time?

Not too long. Let's see. I fear you have to wait till each page re-renders for the sidebar to refresh. 
I triggered a re-render for https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup and now it's there.

**Comment by peterbe** [comment]
But in principle, it seems to work. We just need to wait a bit more.
