### ISSUE TITLE
{{EmbedLiveSample}} should offer a link to open the demo in it's own tab/window

### ISSUE THREAD

**Issue by timdream** [mdn/kumascript#168]
For example, `deviceorientation` events are blocked in iframes. I added a warning below the demo [here](https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation?document_saved=true#Orientation_example) but to make the demo more useful we should offer a link to open the demo in it's own tab/window.

**Comment by a2sheppy** [comment]
I have fixed this on the page in question by adding a sentence explaining this situation and linking to the example in its own window/tab. This involved no changes to anything in this repo.
