### ISSUE TITLE
WebExtBrowserCompatTable macro should support "alternative_name"

### ISSUE THREAD

**Issue by wbamberg** [mdn/kumascript#221]
This PR: https://github.com/mdn/browser-compat-data/pull/263 uses `alternative_name`, which the [WebExtension table macro](https://github.com/mozilla/kumascript/blob/master/macros/WebExtBrowserCompatTable.ejs) doesn't support.

Note that at some point we expect a new macro to be ready, that will work for all MDN pages (i.e. JS and CSS as well as WebExtensions) and at that point we will switch over to that table. So depending on when that will happen, it might be better to wait, than to fix this now.

**Comment by Elchi3** [comment]
> Note that at some point we expect a new macro to be ready, that will work for all MDN pages 

This has happened. compat.ejs is the single compat table implementation and webext macros route through it now. ({{compat}} will be changed again for the redesigned compat tables, but alternative_name should be available then, too).
