### ISSUE TITLE
Suggestion: Add a "category" field to GroupData.json

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kumascript#286]
Let's add a "category" field to GroupData.json. This would let us assign each API to a category (Media, Storage, DOM, UX, etc.). It would then be trivial to produce an always-up-to-date page on MDN that lists all APIs grouped by category, so people interested in A/V and media stuff could get right to a list of those APIs.

This would also help us more easily create landing pages for individual technology areas. Imagine a page "Introducing the media APIs" that briefly talks about each API but then includes a generated list of them all below with links to appropriate documentation for each (say, the overview pages and tutorials for each).

We could also then do a categorized list of interfaces, instead of a purely alphabetical list of them like the one on the Web/API page right now (although still maybe in a new location, with a better landing page there).

I expect there are other valuable use cases here. The hardest part would be deciding on a set of categories to use, and even that isn't that hard to do.

**Comment by jpmedley** [comment]
If you want evidence for why this is a good idea, you have only to look at the mess that the performance APIs are in.

**Comment by a2sheppy** [comment]
Exactly. That’s what brought it to mind — because the Performance APIs
share interfaces and methods and whatnot across multiple APIs. It’s a
mishmash that’s unprecedented among Web APIs, I think.

There are certainly other use cases but this is a big one.


Eric Shepherd
Senior Technical Writer, MDN
MDN: https://developer.mozilla.org/
Blog: https://www.bitstampede.com/

On August 16, 2017 at 2:11:45 PM, Joe Medley (notifications@github.com)
wrote:

If you want evidence for why this is a good idea, you have only to look at
the mess that the performance APIs are in.

**Comment by a2sheppy** [comment]
Thinking about it, "category" would need to be allowed to be either a single string or an array of strings, since some things are part of more than one category.
