### ISSUE TITLE
CSSRef causes an error for localized pages without any category

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kumascript#307]
There are currently pages with macro errors in the CSS section when those don't belong to any CSSData "category". (ex. https://developer.mozilla.org/fr/docs/Web/CSS/Valeur_calcul%C3%A9e )
This seems to be due to: 
https://github.com/mdn/kumascript/blob/41d0c3e23c1fb1842d5af1f03ff1f70896300ad2/macros/CSSRef.ejs#L180

where the localized slug is combined with /en-US/... prefix which causes the subpagesExpand method to throw.
I'll propose a simple WIP PR for that.

**Comment by zhangchen915** [comment]
i find [this](https://developer.mozilla.org/zh-CN/docs/Web/API/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%83%E7%B4%A0%E6%B3%A8%E5%86%8C%E8%A1%A8) page maybe have same problem.

**Comment by SphinxKnight** [comment]
@zhangchen915 I've pushed a new commit to fix this, however, the page you are referring to is an API, hence the name (and slug) should not be localized (these are "code" terms which are invariable regarding the locales). If you have the issue w/ the APIRef macro on a page which have a slug with "linguistic" (ie. non-code) terms, feel free to open another issue and ping me :)
