### ISSUE TITLE
Add support for partial_implementation to Compat macro

### ISSUE THREAD

**Issue by snoack** [mdn/kumascript#324]
The `Compat` macro is currently ignoring the [`partial_implementation`](https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md#partial_implementation) information. See mdn/browser-compat-data#380 for an example were it is used.

I suggest to render cells indicating a partial implementation with a yellow background, and to replace `Yes`/`No` with `Partial`, and like `54 (Partial)` if the version support was added is known.

**Comment by Elchi3** [comment]
The redesigned tables (available to MDN beta users) implement yellow cells with "partial". For more info see https://discourse.mozilla.org/t/beta-testing-new-compatability-tables/21269
