### ISSUE TITLE
Add "Client-side web APIs" module to LearnSidebar macro

### ISSUE THREAD

**Issue by fireattack** [mdn/kumascript#335]
As you can see [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript), the [Client-side web APIs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs) module is under `Learn -> Javascript -> Client-side web APIs`. But currently the sidebar doesn't have it at all.

**Comment by fireattack** [comment]
It should also be mentioned somewhere in JS main entry, https://developer.mozilla.org/en-US/docs/Web/JavaScript.

**Comment by teoli2003** [comment]
Befing fixing this (trivial), @chrisdavidmills, has this been omitted on purpose?

**Comment by chrisdavidmills** [comment]
I have not added it yet to the sidebar because it is not finished (there are still two articles left to write). But I guess we could consider adding it given that it is mostly complete. It might give me some extra impetus to find time to complete them ;-)

**Comment by teoli2003** [comment]
I think this is fixed :-)
