### ISSUE TITLE
Compat macro should allow collapsing subfeatures with identical support

### ISSUE THREAD

**Issue by lpd-au** [mdn/kumascript#345]
APIs implemented in the browser-compat-data repo require one subfeature per property and method, which in turn have their own pages with compatibility tables on MDN web docs. However, for interfaces with many properties and methods, this means the support table can become really long. Consider PointerEvent, for example:

_Before:_ Basic support, `tangentialPressure` & `twist`, `PointerEvent.getCoalescedEvents()` (3 rows)
_After:_ Basic support, `PointerEvent()` constructor, `pointerId`, `width`, `height`, `pressure`, `tangentialPressure`, `tiltX`, `tiltY`, `twist`, `pointerType`, `isPrimary`, `getCoalescedEvents()` (13 rows)

It is clear that most of these new rows are bloat, which should be assumed under "Basic support"; almost all of the properties come from the original level 1 specification. Specifically:

- Basic support and `PointerEvent()` constructor have identical data (IE10 is prefixed).
- `pointerId`, `tiltX`, `tiltY` and `isPrimary` have identical data (IE10 is supported).
- `width`, `height`, `pressure` and `pointerType` have near-identical data (IE10 has partial support).
- `tangentialPressure` and `twist` have identical data (new level 2 properties).
- Only `getCoalescedEvents()` is truly unique (experimental level 2 spec extension).

It would be great if the {Compat} macro could display this data as 5 rows instead of 13 by automatically collapsing rows that have identical support, excluding notes.

**Comment by teoli2003** [comment]
Absolutely, we do note collapsing, but we should do these lines collapsing too.

**Comment by jpmedley** [comment]
I think you would want a feature that generally collapses beyond the 'basic support' line. Speaking as someone who's updated a lot a pages, I don't very often see subfeature lines that are identical to the basic support line. (Assuming I'm understanding what you're asking for.)
