### ISSUE TITLE
Compat macro "depth" argument should default to infinite

### ISSUE THREAD

**Issue by wbamberg** [mdn/kumascript#351]
The Compat.ejs macro has a `depth` parameter that tells it how deep to go into subfeatures, when building a compat table.

But there seems to be no way to say "go as deep as there is data" which is generally what I want when building a compat table, otherwise I lose data.

My suggestion would be to make "go as deep as there is data" be the default value for `depth`, so I get that behavior if I omit the parameter. Then I can provide the argument when I want to *restrict* the depth (as I do when building aggregate tables).

**Comment by Elchi3** [comment]
This could probably go with a refactoring which Will proposed in https://github.com/mdn/kumascript/pull/419#pullrequestreview-80647012.

> This code might be easier to maintain if we do one traverseFeatures pass that just flattens everything under the given node into an array of objects with labels like "tabs.create", "tabs.create.createProperties", "tabs.create.createProperties.index" and so on. (...) Then filter this array to contain only the rows we care about, using the depth parameter, and use the filtered version to write the table.
