### ISSUE TITLE
{{APIRef('XMLHttpRequest')}} misses almost all the methods but two

### ISSUE THREAD

**Issue by fireattack** [mdn/kumascript#439]
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

Check the sidebar: only `abort()` and `getResponseHeader()` shows up.
![image](https://user-images.githubusercontent.com/4130991/33694463-ddc4a87e-dabd-11e7-8124-e2f643462391.png)

But apparently XMLHttpRequest has more:

![image](https://user-images.githubusercontent.com/4130991/33694478-f16514d6-dabd-11e7-85e7-5953ebb185a2.png)

I checked the kuma macros of `APIRef` quickly but don't know why.

If it's not a technical issue please let me know, will report to bugzilla instead.

**Comment by wbamberg** [comment]
Hey @fireattack , thanks for filing. Good catch!

This isn't a bug in the macro itself, it's a problem with tagging. The sidebar macro `XMLHttpRequest` uses pages tags to figure out what type of API item a page describes - methods, properties, and so on: https://github.com/mdn/kumascript/blob/master/macros/APIRef.ejs#L70-L78. But many of those method pages don't have the `Method` tag, so are not added.

I checked some of the pages to confirm this, and also added the `Method` tag to https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open, then force-refreshed https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest, and you'll see that the sidebar does now include `open()` as well.

So the fix would be to tag these pages properly, and yes, that would be a docs bug in Bugzilla.

The XMLHttpRequest docs are very important, but also old and definitely in need of improvement...
