### ISSUE TITLE
W3C Community Group Specs vs Editors Draft

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/kumascript#567]
The taxonomy of status for specifications associates "ED" with W3C Editors Draft, and "Draft" for other non-W3C specs.

W3C Community Groups produce pre-standardization specs, which aren't "W3C" specifications - anybody can create a community group and publish any document as W3C CG spec. My guess it that they should be labeled as "Draft" (or maybe some new Experimental label?) - but I don't feel very strongly about it either. 

I think either of the following two things could happen:
* the taxonomy is updated to say that any CG spec can be considered as equivalent to an Editors Draft
* the SpecData file needs to be updated to relabel CG specs with a different status (which I am happy to provide a pull request for)

**Comment by teoli2003** [comment]
Hi, Dom!

I think labelling them as 'Draft' is perfectly fine. As I understand them, they will never move further than this level, unless they become formal "W3C" specifications and in this case they'll move the ED->WD->CR->PR->Rec path.
