### ISSUE TITLE
JsSidebar Tutorials link on german page

### ISSUE THREAD

**Issue by schlagi123** [mdn/kumascript#653]
In the JsSiedbar on the german page the _Tutorials_ link links to the english JavaScript page.
The url _https://developer.mozilla.org/de/docs/Web/JavaScript/Tutorials_ redirect to _https://developer.mozilla.org/en-US/docs/Web/JavaScript_ but should redirect to _https://developer.mozilla.org/de/docs/Web/JavaScript_

I do not know how to fix this issue so that it links to the german page.

**Comment by schlagi123** [comment]
I have fixed this issue by creating a german Tutorials Page with the content:

`<p>REDIRECT <a class="redirect" href="/de/docs/Web/JavaScript">JavaScript [de]</a></p`

**Comment by Elchi3** [comment]
Closing this then
