### ISSUE TITLE
Technical Review Column in LocalizationStatusInSection macro always needed?

### ISSUE THREAD

**Issue by schlagi123** [mdn/kumascript#705]
I think, that the "technical review" column with the in the overview of the LocalizationStatusInSection macro is in the most cases not relevant. Only in the original language english it is relevant, because all translators of the other languages should only translate, and should not care about technical reviews in there language. The reviews must be done in the english language and then the translators must update the other languages.

Because of this reason I think, that this column should not be visible in translated languages. A consequence of this is, that a page status for technical review on pages of translated languages is also not relevant.

**Comment by SphinxKnight** [comment]
The thing is that all contributors might not be aware that "en-US" is the "certified" source of truth. Thus, some editors occasionally add some new bits in an already localized article, bits that maybe aren't in the English article for some time.

So, my 2 cents, even if I'm not taking any "localized technical reviews", I'll be in favor of keeping that info in doc status pages for localization.

**Comment by schlagi123** [comment]
With this point of view you are right. Then this is everything ok for me.

Close #705
