### ISSUE TITLE
Macro for IETF drafts?

### ISSUE THREAD

**Issue by FranklinYu** [mdn/kumascript#725]
Currently we have macro for RFC link. Is there macro for draft? For example, [the Set-Cookie header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) refers to some IETF drafts. If there is no such macro, do we need it?

Expected code:

```text
{{IETF-draft("ietf-httpbis-cookie-prefixes-00")}}
```

Preview:

> [draft-ietf-httpbis-cookie-prefixes-00](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-prefixes-00)

**Comment by a2sheppy** [comment]
Yes, we should absolutely have this.
