### ISSUE TITLE
Drop "canonical order" in CSS Properties template

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/kumascript#740]
IF I understand this right, the information about the canonical order of the grammar of CSS properties is only useful to browser implementors, not to Web developers (at least not to the vast majority of Web developers).

I think it would make more sense NOT to include that information.

[example of this info raising more questions than answering them](https://stackoverflow.com/questions/28963536/what-does-canonical-order-mean-with-respect-to-css-properties)

**Comment by dontcallmedom** [comment]
yes, I believe this would mean editing cssinfo.ejs, and probably remove the relevant data from mdn/data.

Regarding additional improvements to the box, I think the "Media" field is also of limited value, and one from which the [CSS WG seems to be moving away from](https://github.com/w3c/csswg-drafts/issues/2413#issuecomment-402374797).

For other fields, it would probably be interesting to user-test them to see if they're understandable / useful - my hunch is that they could be more clearly explained, and maybe presented in a more graphical (or least more structured) way.

**Comment by wbamberg** [comment]
I thought this could use a bit more discussion, so I started a [thread about it in Discourse](https://discourse.mozilla.org/t/updates-to-the-css-info-boxes/30855/). It seems like we have something like consensus for removing "Canonical order" and "Media".

**Comment by SebastianZ** [comment]
To copy the statement from [my comment on the Discourse thread](https://discourse.mozilla.org/t/updates-to-the-css-info-boxes/30855/7?u=sebastianzartner), yes, let's remove "Media" and "Canonical order". For the vast majority of properties they don't provide any relevant info. And the cases where they do provide some info can be/are already covered by the textual description of their values.

Sebastian

**Comment by wbamberg** [comment]
Almost 2 years later, this is now done.

I've merged https://github.com/mdn/kumascript/pull/1356, Ryan made a new deployment today and I've refreshed all 1007-odd CSS pages, and "Media" and "Canonical order" are both gone from these boxes.

I'd still like to remove the underlying data from mdn/data, but that's another story.
