### ISSUE TITLE
Intermittent errors in {{bug}}

### ISSUE THREAD

**Issue by wbamberg** [mdn/kumascript#751]
I've been making lots of edits to MDN pages lately, and am often seeing macro errors from the [{{bug}}](https://github.com/mdn/kumascript/blob/master/macros/bug.ejs) macro:

<img width="527" alt="screen shot 2018-07-27 at 10 33 03 am" src="https://user-images.githubusercontent.com/432915/43337354-7bdb8330-9188-11e8-8491-6c9e0dcf2ce2.png">

These are intermittent but seem very common when a lot of pages get updated. I suspect this is because the {{bug}} macro [uses the Bugzilla API](https://github.com/mdn/kumascript/blob/master/macros/bug.ejs#L29-L30), and is being rate-limited.

It uses the Bugzilla API to replace duplicated bugs with the bugs that they duplicate. For example, if I write `{{bug("1411526")}}`, then because [bug 1411526](https://bugzilla.mozilla.org/show_bug.cgi?id=1411526) is duped to [bug 1381992](https://bugzilla.mozilla.org/show_bug.cgi?id=1381992), then the HTML output is: a link to bug 1381992.

Personally I don't think this dupe-walking is very useful, and it would be better to remove it, and this would remove the dependency on the Bugzilla API and fix these intermittent errors.

**Comment by wbamberg** [comment]
> From a brief reading of the bug macro, it appears that the loop de-duplicates bugs, but also reads the description and status. We'd lose this as well if we stopped calling the API.

I'd be interested in knowing how many times this macro is called with a "type" of `table` or `summary` (not often I would guess), as outside those cases this info just goes in a tooltip, and I struggle to see how the value that offers is worth the complexity of the code or the dependency on the Bugzilla API.

> I'd love to see some tests to go along with it.

Yes, I think the PR needs tests (although it does look good).

**Comment by ExE-Boss** [comment]
> > I'd love to see some tests to go along with it.
>
> Yes, I think the PR needs tests (although it does look good).

I don’t really know how I should write a test for that though.

**Comment by emceeaich** [comment]
Use a mock for the BMO API. 

https://medium.freecodecamp.org/how-to-mock-requests-for-unit-testing-in-node-bb5d7865814a

**Comment by a2sheppy** [comment]
The table and summary types are used in extremely limited cases. Probably only on meta-doc style pages and possibly the documentation status pages.

**Comment by emceeaich** [comment]
@dylanwh pointed out in IRC that API calls using keys aren't rate limited, so if kumascript could safely refer to a API key in configuration you can just do that.

**Comment by atopal** [comment]
This just came up again in an email from Chris on December 21. From my point of view, I'd get rid of this functionality instead of spending any time fixing it, considering it's not a small fix.

**Comment by a2sheppy** [comment]
I think we can get rid of de-duping, though. I didn't even know it does that. That'll help a little. That's about the only thing I'd be comfortable with us removing from the other features like the tooltip with the bug summary.

There must be a way we can use a key and the API to get the data we need...

**Comment by dylanwh** [comment]
We can whitelist an IP address or a user-agent as well.

**Comment by dylanwh** [comment]
(we being BMO)

**Comment by a2sheppy** [comment]
@dylanwh brings up the whitelist idea, and I feel like at this time it's our best solution. I think we should remove the de-duping and get whitelisted so that we can quickly resolve this.

**Comment by dylanwh** [comment]
It takes about 1 minute for me to whitelist any number of IPs. User-Agent would have to happen next week as I'd have to implement it.

**Comment by wbamberg** [comment]
>  That's about the only thing I'd be comfortable with us removing from the other features like the tooltip with the bug summary.

I'm hesitant to add more noise into this thread, but: while it's nice that we could potentially avoid getting rate-limited, having this feature in {{bug}} adds more complexity to the macro and an extra dependency to KumaScript, and more opportunities to fail. So it has a nonzero cost, and should provide a nonzero benefit if we want to keep it.

The problem with the bug summary is that very often bug titles are not very helpful, while links to bugs in MDN are usually presented in context anyway. So very often the summary isn't going to add anything.

To make this about more than just opinions, I went through the first 10 occurrences of the {{bug}} macro in our open web docs, and summarised the results here: https://docs.google.com/spreadsheets/d/1Wk-5yw0485_21pLVSyDYPIAb-0QWI-MuZvrhFXgiXk8/edit?usp=sharing.

Column 1 is a link to the page, column 2 is the page content surrounding the bug link, and column 3 is the contents of the title attribute. The question is, is the title attribute content providing any additional useful information that isn't already in the page content? I don't think it is, in any of these cases.

**Comment by atopal** [comment]
Thanks for looking into it Will, and I agree, If anything, I'd suggest we remove this macro

**Comment by atopal** [comment]
Right, in the short term, I'd change the macro to just create a link. That said, I have never looked into it and not sure whether there would be any issues with that.
