### ISSUE TITLE
All pages using `AddonSidebar` display content within `<strong>`

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kumascript#769]
Creating an issue to replicate https://discourse.mozilla.org/t/why-is-all-normal-text-bold-now/31038 here.

**Comment by ExE-Boss** [comment]
I also opened #771 to fix a remaining `<a>` and `<strong>` DOM hierarchy issue.

**Comment by SphinxKnight** [comment]
@wbamberg yes, thanks for the reminder :)
