### ISSUE TITLE
iframe macros needs to add an "allow" argument for feature-policy

### ISSUE THREAD

**Issue by Artoria2e5** [mdn/kumascript#787]
The [feature policy](https://wicg.github.io/feature-policy/) proposal ([firefox bz1390801](https://bugzilla.mozilla.org/show_bug.cgi?id=1390801), [chromium doc](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes)) is going to make a few features unavailable by default in an `<iframe>`. The implementation currentlu shipped in Chromium breaks the example at [MDN:Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API).

To adapt to this change, EmbedLiveSample macro should either always include all possible `allow` values by default (`geolocation; microphone; camera; midi; encrypted-media`), or add an argument to let callers pass in this value. The former solution is not as unsafe as it sounds, as without an origin given the grants only apply to the origin specified in `src`.

**Comment by Artoria2e5** [comment]
Oh, it looks like this change affects a few other macros too. From https://github.com/mdn/kumascript/search?utf8=✓&q=iframe:
* JSFiddleEmbed
* EmbedGHLiveSample
* EmbedLiveSample
* EmbedInteractiveExample
* EmbedSVG (if people ever write an svg with midi sounds?)

**Comment by jwhitlock** [comment]
This is also tracked in [bug 1482159](https://bugzilla.mozilla.org/show_bug.cgi?id=1482159). The fix for ``EmbedLiveSample`` is in PR #786. I want similar testing for other ``Embed*`` macros.

I think we'll continue adding an optional macro parameter to populate the ``allow`` attribute if a sample requires it. Most samples don't, and it is useful information that a sample requires access to a restricted feature.

**Comment by jpmedley** [comment]
@chrisdavidmills Chris and I discussed this a month ago. There is a solution in the pipe, be he has more direct knowledge of it.

Because Chrome has implemented much of this, I also have a bunch of new docs related to feature policy that I'll be putting on MDN in the coming weeks. It would be up already but I'm having trouble getting implementors to understand that Wiki does not equal 'anything goes'.

**Comment by chrisdavidmills** [comment]
@jpmedley because only a small subset of samples are affected, the conclusion we came to was to add the parameter to the macro, which is what John's PR referenced above does. This was seen as easier and cleaner than adding feature-policy to the whole site.

**Comment by jpmedley** [comment]
I still think that's only a short-term solution. I hope you're at least considering the possibility that some browser will chose to implement headers ahead of `allow`.

**Comment by jwhitlock** [comment]
@jpmedley is there a browser that enforces feature policy and allows exceptions only via the header? Or one that is planning to ship? I still plan to go with the ``<iframe allow="...">`` solution, but it would be good to know how long we have for the header solution.

**Comment by jpmedley** [comment]
Not that I know of. If it happens you'll be scrambling.

**Comment by jwhitlock** [comment]
All the relevant PRs have been shipped to production:

- https://github.com/mdn/kumascript/pull/777 - Configure sample server URL
- https://github.com/mdn/kumascript/pull/785 - Test EmbedLiveSample
- https://github.com/mdn/kumascript/pull/786 - Set <iframe allow=> attribute
- https://github.com/mdn/infra/pull/46 - Configure sample server URL
- https://github.com/mozilla/kuma/pull/4940 - Refactor iframe allow list
- https://github.com/mozilla/kuma/pull/4950 - SSL configuration
- https://github.com/mozilla/kuma/pull/4951 - Configure sample server URL
- https://github.com/mozilla/kuma/pull/4952 - Refactor content cleaning
- https://github.com/mozilla/kuma/pull/4953 - Disable iframe filtering, or extend patterns
- https://github.com/mozilla/kuma/pull/4956 - Allow <iframe allow=> attribute

I've updated these pages, and the live examples work in Firefox, Chrome, and Safari:
* https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints#Result ([diff](https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints$compare?to=1411870&from=1401022))
* https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#Live_Result ([diff](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API$compare?to=1411873&from=1409922))

There may be other pages that require feature policy allow lists, please use a similar change to fix them. No issue is needed, just fix it 😁 

I haven't updated the other macros that include iframes, and I don't intend to, unless there is a broken example that relies on it. If you find one, please open an issue with the broken MDN page, we'll start that work.

> Not that I know of. If it happens you'll be scrambling.

Thanks for your concern @jpmedley. I have to prioritize other work over implementing the header-based solution.  Please open a new issue if you believe strongly in this and want to escalate.
