### ISSUE TITLE
{{CompatGeckoDesktop}} macro uses zone vanity URLs

### ISSUE THREAD

**Issue by jwhitlock** [mdn/kumascript#799]
URLs should be updated from https://developer.mozilla.org/en-US/Firefox to developer.mozilla.org/en-US/docs/Mozilla/Firefox, to reflect the changes from [bug 1462475](https://bugzilla.mozilla.org/show_bug.cgi?id=1462475).

https://github.com/mdn/kumascript/blob/b566c863c733b7ee3757f65bb5c6e32967ad80e1/macros/CompatGeckoDesktop.ejs#L137

We're using this macro [less](https://developer.mozilla.org/en-US/search?locale=en-US&kumascript_macros=CompatGeckoDesktop&topic=none) with the BCD project, but it will continue being used on Events pages, like https://developer.mozilla.org/en-US/docs/Web/Events/addstream, while we decide if and how to migrate the data.

A macro test for ``CompatGeckoDesktop`` would be nice as well.

**Comment by ExE-Boss** [comment]
Well, the legacy `{{Compat*}}` macros are deprecated and will probably be going away once [the browser‑compat‑data migration](https://developer.mozilla.org/docs/MDN/Contribute/Structures/Compatibility_tables) is complete.
