### ISSUE TITLE
What does the {{IncludeSubnav}} macro actually do?

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/kumascript#804]
[The `{{IncludeSubnav}}` macro documentation states:](https://github.com/mdn/kumascript/blob/master/macros/IncludeSubnav.ejs) https://github.com/mdn/kumascript/blob/e57e27c371416c7e104f7843318e9166dbe3c1f3/macros/IncludeSubnav.ejs#L2-L9

But what does “Inserts the contents of a sub navigation into the document.” actually mean?

I have tried to look at pages that make use of this macro, but I can’t seem to be able to figure out what the macro does to those pages.

**Comment by jwhitlock** [comment]
The subnav was a feature of zones, where you could create something like a sidebar in the root page of a zone, and it would be automatically included in child pages. In some ways it is better than our macro-based sidebars. They we dropped with zones (https://github.com/mozilla/kuma/pull/4853), and should be replaced by a sidebar macro, such as ``{{GamesSidebar}}``

**Comment by ExE-Boss** [comment]
I have been repurposing the `{{IncludeSubnav}}` macro for pages which don’t have an associated sidebar macro, but for which I still want a custom sidebar:
```html
<div>
<h2>Subnav</h2>
<section id="Quick_Links">
<!-- Custom sidebar code goes here -->
</section>
</div>
```

Pages which make use of this:
- https://developer.mozilla.org/en-US/docs/Archive (I’ve converted the Subnav and {{ListSubpages}} macro call that was on the page into using the {{QuickLinksWithSubpages}} macro) 
  - https://developer.mozilla.org/en-US/docs/Archive/Web
- https://developer.mozilla.org/en-US/docs/Archive/B2G_OS (contains a static version of the now removed {{Firefox_OS_Sidebar}} macro)
- https://developer.mozilla.org/en-US/docs/User:stephaniehobson
- https://developer.mozilla.org/en-US/docs/User:ExE-Boss
  - https://developer.mozilla.org/en-US/docs/User:ExE-Boss/KumaScript_OnePage_replacement
  - https://developer.mozilla.org/en-US/docs/User:ExE-Boss/KumaScript_OnePage_replacement/WebExtAllCompatTables
